version: "3.9"

services:
  backend:
    build:
      context: ./IMDB
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./IMDB:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
