name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./IMDB
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/imdb-backend:latest

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/imdb-frontend:latest
